[workspace]
members = [
    "canisters/merchant",
    "canisters/agent"
]

[workspace.dependencies]
candid = "0.9"
ic-cdk = "0.11"
icrc-ledger-types = "0.1.0"
serde = "1.0"
serde_json = "1.0"
base64 = "0.21"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1